name: Test RDS Connection

on:
  push:

jobs:
  test-db:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for RDS to be ready
        run: |
          echo "Esperando a que RDS esté disponible..."

          for i in {1..30}; do
            nc -zv ${{ secrets.DB_HOST }} 5432 && echo "RDS listo" && exit 0
            echo "Intento $i: aún no disponible..."
            sleep 10
          done

          echo "RDS no respondió a tiempo"
          exit 1

      - name: Test connection
        run: |
          echo "Probando conexión..."

          PGPASSWORD=${{ secrets.DB_PASSWORD }} psql \
            -h ${{ secrets.DB_HOST }} \
            -U ${{ secrets.DB_USER }} \
            -d postgres \
            -c "SELECT 1;"